### ISSUE TITLE
Possible quicker access to API data

### ISSUE THREAD

**Issue by Waterproof21** [TheCookieLab/poloniex-api-java#31]
Hi,

First of all great work. 

Is there any way, in which I would be able to receive ticker oder balance values from the Poloniex API more quickly?
Since when using the API there are rather often wait times of more than 60 seconds for just one ticker or balance value.

Best Regards

**Comment by TheCookieLab** [comment]
If you’re interested in seeing how long the API call + mapping takes, you can turn on trace level logging. There’s negligible overhead introduced by the code; the delay you experience is due to Poloniex’s response time and/or your location.

If you need faster ticker data, you should use the websocket functionality (which I’m putting the finishing touches on and should be ready soon).
